[package]
name = "api"
version = "0.3.25"
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
by-axum.workspace = true
by-types.workspace = true

models = { workspace = true, features = ["server"] }

serde_json.workspace = true
serde.workspace = true
chrono = { workspace = true, features = ["now"] }
reqwest.workspace = true
slog.workspace = true
sqlx.workspace = true
rest-api.workspace = true

tokio = { version = "1.41.1", features = ["full"] }
jsonwebtoken = "9.3.0"
sha3 = "0.10.8"
uuid = { version = "1.11.0", features = ["v4"] }
aws-sdk-sesv2 = "1.54.0"
aws-config = "1.5.10"
rand = "0.8.5"
lazy_static = "1.5.0"

futures = "0.3.31"
schemars = "0.8.21"
tracing = "0.1.41"
validator = "0.20.0"
rust_xlsxwriter = "0.84.0"
aws-sdk-s3 = "1.74.0"
aws-sdk-chimesdkmeetings = "1.63.0"
aws-sdk-chimesdkmediapipelines = "1.64.0"

[features]
default = []
lambda = ["by-axum/lambda"]
full-test = []

[dev-dependencies]
tower = "0.5.2"
rest-api.workspace = true
